module.exports = {
  CHAT: "CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  VERIFY_USER: "VERIFY_USER",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  CODING: "CODING",
  TEST_CHECK: "TEST_CHECK",
  LOGOUT: "LOGOUT"
};